langs extended for dist
heathermiller/dist-prog-book pull request #14
Opened 2016-12-16 19:55 UTC by howell

2016-12-16 20:26 UTC, pgrosu requested changes
Really awesome Sam (especially the Macros :)!  Just a few spelling thingies.

2016-12-16 20:26 UTC, pgrosu commented on chapter/5/langs-extended-for-dist.md
> +Erik Meijer points out in {% cite salesman --file langs-extended-for-dist %} that programmers don't jump to new techonologies to access new features. Rather, in time those features make their way to
s/techonologies/technologies

2016-12-16 20:26 UTC, pgrosu commented on chapter/5/langs-extended-for-dist.md
> +idea, but enjoy the benefits of the library/extension appraoch. Both Linda and Lasp take this approach, for example.
s/appraoch/approach

2016-12-16 20:26 UTC, pgrosu commented on chapter/5/langs-extended-for-dist.md
> +large-scale data. MapReduce (and correspondingly Hadoop) is the landmark example of a programming model for distributed batch processing. Essentially, batch processing systems present a restricted pr
s/aggregrate/aggregate

2016-12-16 20:26 UTC, pgrosu commented on chapter/5/langs-extended-for-dist.md
> +numbers is instead sent a string. Anecodatally, typed actors in Akka are not commonly used. This might suggest that errors due to incorrect message types are not that serious of a concern for users.
s/Anecodatally/Anecdotally

2016-12-16 20:26 UTC, pgrosu commented on chapter/5/langs-extended-for-dist.md
> +The final approach to consider is similar to extending a language, but this time doing so only by writing code in that language to create new abstractions implementing a language model. This strategy
s/moreso/more so

2016-12-18 21:08 UTC, heathermiller commented
Merging so it's up on the site, I'll follow up with comments/edits soon :)

2016-12-18 21:08 UTC, merged